apiVersion: v1
kind: PersistentVolume
metadata:
  name: jeg-kernelspec-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/jeg/kernelspecs/
    type: Directory
