apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jeg-kernelspec-pvc
  namespace: jeg
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: "" # Required for static provisioning in Minikube
