kind: Pod
apiVersion: v1
metadata:
  name: nfs-direct
  namespace: storage
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: data
      mountPath: /tmp/data
  volumes:
  - name: data
    nfs:
      server: 10.110.207.173 # "nfs-service.storage.svc.cluster.local" # replace with the NFS service IP address
      path: "/data/nfs" # "nfs-direct" folder must exist inside "/exports" directory of NFS server
