apiVersion: v1
kind: Service
metadata:
  name: jupyter-enterprise-gateway
  namespace: jeg
spec:
  selector:
    app: enterprise-gateway
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
  type: NodePort
