on:
  push:
    branches:
      - kernelspec-image
    paths:
      - 'kernelspecs/**'
  pull_request:
    paths:
      - 'kernelspecs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build kernelspec image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: kernelspecs/kernelspec.dockerfile
          push: true
          tags: kernelspecs-image:latest